spring:
  datasource:
    primary:
      url: jdbc:postgresql://localhost:5400/product
      driver-class-name: org.postgresql.Driver
      username: boss
      password: 123456
    replica:
      url: jdbc:postgresql://localhost:5500/product
      driver-class-name: org.postgresql.Driver
      username: boss
      password: 123456

  liquibase:
    change-log: classpath:db/changelog-master.yml

  jpa:
    open-in-view: false